<?php

namespace App\Services\Hr;

use App\Contracts\Hr\PayrollServiceInterface;
use App\Models\Payroll;
use App\Models\PayrollItem;
use App\Models\Employee;
use App\Models\Attendance;
use App\Models\EmployeeDeduction;
use App\Models\TechnicianCommission;
use App\Models\EmployeeLeave;
use App\Models\EmployeePayrollDebt;
use App\Models\Branch;
use App\Models\User;
use App\Notifications\PayrollGeneratedNotification;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Exception;

class PayrollService implements PayrollServiceInterface
{
    /**
     * {@inheritDoc}
     */
    public function getPayrollIndexData(?int $branchId = null, int $perPage = 15): array
    {
        $branches = Branch::where('is_active', true)->get();
        $employees = Employee::active()->with(['branch', 'jobTitle.department', 'currentSalary'])->get();
        $recentDeductions = EmployeeDeduction::with(['employee', 'approvedByUser'])->latest('id')->take(20)->get();

        $query = Payroll::with(['branch', 'approvedBy', 'items.employee.jobTitle'])->latest('id');

        if (!empty($branchId)) {
            $query->where('branch_id', $branchId);
        }

        $payrolls = $query->paginate($perPage);
        $latestPayroll = (clone $query)->first();

        return compact('payrolls', 'branches', 'employees', 'recentDeductions', 'latestPayroll');
    }

    /**
     * {@inheritDoc}
     */
    public function generateMonthlyPayroll(int $branchId, int $year, int $month): Payroll
    {
        return DB::transaction(function () use ($branchId, $year, $month) {
            $existing = Payroll::where('branch_id', $branchId)->where('year', $year)->where('month', $month)->first();
            if ($existing && $existing->status === 'disbursed') {
                throw new Exception("لا يمكن إعادة احتساب مسير رواتب تم صرفه وإغلاقه بالفعل.");
            }

            if ($existing && $existing->status === 'approved') {
                throw new Exception("لا يمكن إعادة احتساب مسير رواتب معتمد. يجب إعادته إلى المسودة أولاً.");
            }

            $payroll = Payroll::updateOrCreate(
                ['branch_id' => $branchId, 'year' => $year, 'month' => $month],
                ['status' => 'draft']
            );

            // Remove debt records generated by the previous draft items before
            // replacing those items, so recalculation cannot duplicate debt.
            $oldItemIds = $payroll->items()->pluck('id');

            if ($oldItemIds->isNotEmpty()) {
                EmployeePayrollDebt::whereIn('source_payroll_item_id', $oldItemIds)->delete();
            }

            // حذف البنود القديمة لإعادة الاحتساب بدقة
            $payroll->items()->delete();

            $startDate = Carbon::createFromDate($year, $month, 1)->startOfMonth();
            $endDate   = $startDate->copy()->endOfMonth();
            $totalMonthDays = $startDate->daysInMonth;

            $employees = Employee::with(['currentSalary'])
                ->where('branch_id', $branchId)
                ->where('status', 'active')
                ->get();

            $employeeIds = $employees->pluck('id');

            // ─── جلب كل بيانات الحضور والإجازات والعمولات والجزاءات دفعة واحدة (4 استعلامات فقط بدلاً من 4N) ───
            $allAttendances = Attendance::whereIn('employee_id', $employeeIds)
                ->whereBetween('work_date', [$startDate->toDateString(), $endDate->toDateString()])
                ->get()
                ->groupBy('employee_id');

            $allLeaves = EmployeeLeave::whereIn('employee_id', $employeeIds)
                ->where('status', 'approved')
                ->where(function ($query) use ($startDate, $endDate) {
                    $query->whereDate('start_date', '<=', $endDate->toDateString())
                          ->whereDate('end_date', '>=', $startDate->toDateString());
                })
                ->get()
                ->groupBy('employee_id');

            $allCommissions = TechnicianCommission::whereIn('employee_id', $employeeIds)
                ->where('status', 'approved')
                ->whereBetween('created_at', [$startDate, $endDate])
                ->get()
                ->groupBy('employee_id');

            $allDeductions = EmployeeDeduction::whereIn('employee_id', $employeeIds)
                ->where('status', 'approved')
                ->whereBetween('deduction_date', [$startDate->toDateString(), $endDate->toDateString()])
                ->get()
                ->groupBy('employee_id');

            // Outstanding payroll debts are carried forward and can only be
            // recovered from a positive amount available after current deductions.
            $outstandingDebts = EmployeePayrollDebt::whereIn('employee_id', $employeeIds)
                ->whereNull('settled_at')
                ->get()
                ->groupBy('employee_id');
            // ────────────────────────────────────────────────────────────────────────────────────────────

            $totalBasic       = 0;
            $totalAllowances  = 0;
            $totalDeductions  = 0;
            $totalNet         = 0;

            foreach ($employees as $employee) {
                $salary = $employee->currentSalary;
                if (!$salary) continue;

                $basic      = (float) $salary->basic_salary;
                $allowances = (float) ($salary->housing_allowance + $salary->transport_allowance + $salary->other_allowances);
                $dayRate    = $basic / $totalMonthDays;
                $hourlyRate = $dayRate / 8; // شفت 8 ساعات عمل

                // 1. حساب الحضور والغياب والإجازات والتأخير (من الذاكرة — بدون استعلام)
                $attendances = $allAttendances->get($employee->id, collect());
                $employeeLeaves = $allLeaves->get($employee->id, collect());

                $paidLeaveDays = 0;
                $unpaidLeaveDays = 0;

                foreach ($employeeLeaves as $leave) {
                    $leaveStart = Carbon::parse($leave->start_date)->startOfDay();
                    $leaveEnd = Carbon::parse($leave->end_date)->startOfDay();
                    $windowStart = $startDate->copy()->startOfDay();
                    $windowEnd = $endDate->copy()->startOfDay();

                    $effectiveStart = $leaveStart->greaterThan($windowStart) ? $leaveStart : $windowStart;
                    $effectiveEnd = $leaveEnd->lessThan($windowEnd) ? $leaveEnd : $windowEnd;

                    if ($effectiveStart->lessThanOrEqualTo($effectiveEnd)) {
                        $days = (int) $effectiveStart->diffInDays($effectiveEnd) + 1;
                        if ($leave->leave_type === 'unpaid') {
                            $unpaidLeaveDays += $days;
                        } else {
                            $paidLeaveDays += $days;
                        }
                    }
                }

                $presentDays         = $attendances->where('status', '!=', 'absent')->count();
                $coveredDays         = $presentDays + $paidLeaveDays;
                $unexcusedAbsentDays = max(0, 26 - $coveredDays); // معيار 26 يوم عمل شهري
                $absentDays          = $unexcusedAbsentDays + $unpaidLeaveDays;
                $absenceCost         = $absentDays * $dayRate;

                $totalLateMinutes  = $attendances->sum('late_minutes');
                $totalOvertimeHours = (float) $attendances->sum('overtime_hours');
                $overtimeValue     = round($totalOvertimeHours * $hourlyRate * 1.5, 2);

                // 2. تجميع عمولات الفني (من الذاكرة — بدون استعلام)
                $commissions = (float) $allCommissions->get($employee->id, collect())->sum('commission_amount');

                // 3. تجميع الجزاءات المعتمدة (من الذاكرة — بدون استعلام)
                $approvedDeductions = (float) $allDeductions->get($employee->id, collect())->sum('amount');

                $grossSalary = round($basic + $allowances + $overtimeValue + $commissions, 2);
                $currentDeductions = round($absenceCost + $approvedDeductions, 2);
                $availableAfterCurrentDeductions = round($grossSalary - $currentDeductions, 2);

                $employeeDebt = round(
                    $outstandingDebts->get($employee->id, collect())
                        ->sum(fn ($debt) => max(0, (float) $debt->original_amount - (float) $debt->paid_amount)),
                    2
                );

                $debtRepayment = $employeeDebt > 0
                    ? min(max(0, $availableAfterCurrentDeductions), $employeeDebt)
                    : 0;

                // If current deductions exceed gross earnings, preserve the
                // unrecovered balance as an employee debt instead of losing it.
                $currentShortfall = max(0, round(-$availableAfterCurrentDeductions, 2));
                $carriedDebt = $currentShortfall;
                $netSalary = round(max(0, $availableAfterCurrentDeductions - $debtRepayment), 2);
                $allDeductionsTotal = round($currentDeductions + $debtRepayment, 2);

                $payrollItem = PayrollItem::create([
                    'payroll_id'         => $payroll->id,
                    'employee_id'        => $employee->id,
                    'basic_salary'       => $basic,
                    'total_allowance'    => $allowances + $commissions,
                    'total_deduction'    => $allDeductionsTotal,
                    'debt_repayment'     => $debtRepayment,
                    'carried_debt'       => $carriedDebt,
                    'total_overtime'     => $overtimeValue,
                    'net_salary'         => $netSalary,
                    'absent_days'        => $absentDays,
                    'late_minutes_total' => $totalLateMinutes,
                ]);

                if ($carriedDebt > 0) {
                    EmployeePayrollDebt::create([
                        'employee_id' => $employee->id,
                        'source_payroll_item_id' => $payrollItem->id,
                        'original_amount' => $carriedDebt,
                        'paid_amount' => 0,
                    ]);
                }

                $totalBasic      += $basic;
                $totalAllowances += ($allowances + $commissions);
                $totalDeductions += $allDeductionsTotal;
                $totalNet        += $netSalary;
            }

            $payroll->update([
                'total_basic'      => $totalBasic,
                'total_allowances' => $totalAllowances,
                'total_deductions' => $totalDeductions,
                'total_net'        => $totalNet,
            ]);

            // Keep the batch in draft whenever an employee has an unrecovered
            // payroll balance. The review is explicit; the system must not
            // silently present a zero net as ready for disbursement.
            if ($payroll->items()->where('carried_debt', '>', 0)->exists()) {
                $payroll->update(['status' => 'draft']);
            }

            // إشعار المشرف العام بأن المسير جاهز للاعتماد
            $superAdmins = User::role('super-admin')->get();
            foreach ($superAdmins as $superAdmin) {
                $superAdmin->notify(new PayrollGeneratedNotification($payroll));
            }

            return $payroll;
        });
    }

    /**
     * Validate payroll header totals against its immutable item breakdown.
     *
     * The item rows are the source of truth for approval/disbursement.
     * Historical records with inconsistent stored totals must never be silently
     * approved or disbursed.
     */
    private function assertPayrollTotalsConsistent(Payroll $payroll): void
    {
        $items = $payroll->items()->get();

        $basic = round((float) $items->sum('basic_salary'), 2);
        $allowances = round((float) $items->sum('total_allowance'), 2);
        $deductions = round((float) $items->sum('total_deduction'), 2);
        $net = round((float) $items->sum('net_salary'), 2);
        $carriedDebt = round((float) $items->sum('carried_debt'), 2);

        $expectedNet = round($basic + $allowances - $deductions + $carriedDebt, 2);

        $headerMismatch =
            abs((float) $payroll->total_basic - $basic) > 0.01 ||
            abs((float) $payroll->total_allowances - $allowances) > 0.01 ||
            abs((float) $payroll->total_deductions - $deductions) > 0.01 ||
            abs((float) $payroll->total_net - $net) > 0.01;

        $netMismatch = abs($net - $expectedNet) > 0.01;
        $zeroWithComponents = abs($net) < 0.01 && ($basic + $allowances > 0 || $deductions > 0);

        if ($headerMismatch || $netMismatch || $zeroWithComponents) {
            throw new Exception(
                "لا يمكن اعتماد أو صرف مسير الرواتب: إجماليات المسير لا تتطابق مع بنوده. " .
                "المتوقع صافي {$expectedNet} ج.م، والمسجل {$net} ج.م. يجب تصحيح المسير قبل المتابعة."
            );
        }
    }

    /**
     * {@inheritDoc}
     */
    public function approvePayroll(Payroll $payroll, ?int $approvedBy = null, bool $confirmDebtReview = false): bool
    {
        if ($payroll->status !== 'draft') {
            throw new Exception("المسير معتمد مسبقاً أو تم صرفه.");
        }

        $this->assertPayrollTotalsConsistent($payroll);

        $hasUnrecoveredDebt = $payroll->items()->where('carried_debt', '>', 0)->exists();

        if ($hasUnrecoveredDebt && !$confirmDebtReview) {
            throw new Exception("يوجد موظفون لديهم أرصدة رواتب غير مستردة. يجب مراجعة الرصيد المرحّل والتأكيد قبل اعتماد المسير.");
        }

        $approverId = $approvedBy ?? Auth::id();

        if (empty($approverId)) {
            throw new Exception("يجب تحديد المستخدم المعتمِد — لا يمكن اعتماد مسير الرواتب بدون تسجيل المسؤول.");
        }

        return $payroll->update([
            'status'      => 'approved',
            'approved_by' => $approverId,
        ]);
    }

    /**
     * {@inheritDoc}
     */
    public function disbursePayroll(Payroll $payroll): bool
    {
        return DB::transaction(function () use ($payroll) {
            $payroll = Payroll::query()->lockForUpdate()->findOrFail($payroll->id);

            if ($payroll->status !== 'approved') {
                throw new Exception("يجب اعتماد مسير الرواتب أولاً قبل الصرف.");
            }

            $this->assertPayrollTotalsConsistent($payroll);

            $items = $payroll->items()->lockForUpdate()->get();

            foreach ($items as $item) {
                $remainingRepayment = (float) $item->debt_repayment;

                if ($remainingRepayment <= 0) {
                    continue;
                }

                $debts = EmployeePayrollDebt::where('employee_id', $item->employee_id)
                    ->whereNull('settled_at')
                    ->lockForUpdate()
                    ->orderBy('id')
                    ->get();

                foreach ($debts as $debt) {
                    if ($remainingRepayment <= 0) {
                        break;
                    }

                    $remainingDebt = max(0, (float) $debt->original_amount - (float) $debt->paid_amount);
                    $payment = min($remainingRepayment, $remainingDebt);

                    if ($payment <= 0) {
                        continue;
                    }

                    $debt->paid_amount = round((float) $debt->paid_amount + $payment, 2);

                    if ((float) $debt->paid_amount >= (float) $debt->original_amount) {
                        $debt->paid_amount = $debt->original_amount;
                        $debt->settled_at = now();
                    }

                    $debt->save();
                    $remainingRepayment = round($remainingRepayment - $payment, 2);
                }

                if ($remainingRepayment > 0.01) {
                    throw new Exception("تعذر مطابقة كامل سداد دين الرواتب للموظف رقم {$item->employee_id}. لم يتم صرف المسير.");
                }
            }

            return $payroll->update([
                'status' => 'disbursed',
                'disbursed_at' => now(),
            ]);
        });
    }

    /**
     * {@inheritDoc}
     */
    public function getPayrollDetails(Payroll $payroll): Payroll
    {
        return $payroll->load(['branch', 'items.employee.jobTitle', 'approvedBy']);
    }
}
