<?php

namespace App\Services\Hr;

use App\Contracts\Hr\PayrollServiceInterface;
use App\Models\Payroll;
use App\Models\PayrollItem;
use App\Models\Employee;
use App\Models\Attendance;
use App\Models\EmployeeDeduction;
use App\Models\TechnicianCommission;
use App\Models\EmployeeLeave;
use App\Models\EmployeePayrollDebt;
use App\Models\Branch;
use App\Models\User;
use App\Notifications\PayrollGeneratedNotification;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Exception;

class PayrollService implements PayrollServiceInterface
{
    /**
     * {@inheritDoc}
     */
    public function getPayrollIndexData(?int $branchId = null, int $perPage = 15): array
    {
        $branches = Branch::where('is_active', true)->get();
        $employees = Employee::active()->with(['branch', 'jobTitle.department', 'currentSalary'])->get();
        $recentDeductions = EmployeeDeduction::with(['employee', 'approvedByUser'])->latest('id')->take(20)->get();

        $query = Payroll::with(['branch', 'approvedBy', 'items.employee.jobTitle'])->latest('id');

        if (!empty($branchId)) {
            $query->where('branch_id', $branchId);
        }

        $payrolls = $query->paginate($perPage);
        $latestPayroll = (clone $query)->first();

        // Consistency is computed once, server-side, with the same rules used by approve/disburse,
        // so the register view never re-implements (and drifts from) the payroll formula.
        $payrollConsistency = $payrolls->getCollection()
            ->mapWithKeys(fn (Payroll $payroll) => [$payroll->id => $this->evaluateConsistency($payroll)])
            ->all();

        // Latest stored payroll item per employee (the breakdown and payslip show stored values,
        // never client-side estimates).
        $latestItems = PayrollItem::whereIn('employee_id', $employees->pluck('id'))
            ->with('payroll:id,branch_id,year,month,status')
            ->get()
            ->sortByDesc(fn (PayrollItem $item) => [$item->payroll->year, $item->payroll->month, $item->id])
            ->unique('employee_id')
            ->keyBy('employee_id');

        return compact('payrolls', 'branches', 'employees', 'recentDeductions', 'latestPayroll', 'payrollConsistency', 'latestItems');
    }

    /**
     * {@inheritDoc}
     */
    public function generateMonthlyPayroll(int $branchId, int $year, int $month): Payroll
    {
        return DB::transaction(function () use ($branchId, $year, $month) {
            $existing = Payroll::where('branch_id', $branchId)->where('year', $year)->where('month', $month)->first();
            if ($existing && $existing->status === 'disbursed') {
                throw new Exception("لا يمكن إعادة احتساب مسير رواتب تم صرفه وإغلاقه بالفعل.");
            }

            if ($existing && $existing->status === 'approved') {
                throw new Exception("لا يمكن إعادة احتساب مسير رواتب معتمد. يجب إعادته إلى المسودة أولاً.");
            }

            $payroll = Payroll::updateOrCreate(
                ['branch_id' => $branchId, 'year' => $year, 'month' => $month],
                ['status' => 'draft']
            );

            // Remove debt records generated by the previous draft items before
            // replacing those items, so recalculation cannot duplicate debt.
            $oldItemIds = $payroll->items()->pluck('id');

            if ($oldItemIds->isNotEmpty()) {
                EmployeePayrollDebt::whereIn('source_payroll_item_id', $oldItemIds)->delete();
            }

            // حذف البنود القديمة لإعادة الاحتساب بدقة
            $payroll->items()->delete();

            $startDate = Carbon::createFromDate($year, $month, 1)->startOfMonth();
            $endDate   = $startDate->copy()->endOfMonth();
            $totalMonthDays = $startDate->daysInMonth;

            // Employees on approved leave are still on payroll: paid and unpaid leave days are
            // computed below, so excluding status on_leave silently dropped them (BIZ-09).
            $employees = Employee::with(['currentSalary'])
                ->where('branch_id', $branchId)
                ->whereIn('status', ['active', 'on_leave'])
                ->get();

            $employeeIds = $employees->pluck('id');

            // ─── جلب كل بيانات الحضور والإجازات والعمولات والجزاءات دفعة واحدة (4 استعلامات فقط بدلاً من 4N) ───
            $allAttendances = Attendance::whereIn('employee_id', $employeeIds)
                // whereDate (not whereBetween on Y-m-d strings): date-cast columns are stored as
                // 'Y-m-d 00:00:00' on SQLite, which a string upper bound of 'Y-m-d' would exclude.
                ->whereDate('work_date', '>=', $startDate->toDateString())
                ->whereDate('work_date', '<=', $endDate->toDateString())
                ->get()
                ->groupBy('employee_id');

            $allLeaves = EmployeeLeave::whereIn('employee_id', $employeeIds)
                ->where('status', 'approved')
                ->where(function ($query) use ($startDate, $endDate) {
                    $query->whereDate('start_date', '<=', $endDate->toDateString())
                          ->whereDate('end_date', '>=', $startDate->toDateString());
                })
                ->get()
                ->groupBy('employee_id');

            $allCommissions = TechnicianCommission::whereIn('employee_id', $employeeIds)
                ->where('status', 'approved')
                ->whereBetween('created_at', [$startDate, $endDate])
                ->get()
                ->groupBy('employee_id');

            $allDeductions = EmployeeDeduction::whereIn('employee_id', $employeeIds)
                ->where('status', 'approved')
                ->whereDate('deduction_date', '>=', $startDate->toDateString())
                ->whereDate('deduction_date', '<=', $endDate->toDateString())
                ->get()
                ->groupBy('employee_id');

            // Outstanding payroll debts are carried forward and can only be
            // recovered from a positive amount available after current deductions.
            $outstandingDebts = EmployeePayrollDebt::whereIn('employee_id', $employeeIds)
                ->whereNull('settled_at')
                ->get()
                ->groupBy('employee_id');
            // ────────────────────────────────────────────────────────────────────────────────────────────

            $totalBasic       = 0;
            $totalAllowances  = 0;
            $totalDeductions  = 0;
            $totalNet         = 0;

            // Settings → payroll norms (defaults are the previously hard-coded values).
            $normWorkingDays   = (int) \App\Models\Setting::number('monthly_working_days', 26, 1, 31);
            $dailyWorkingHours = \App\Models\Setting::number('daily_working_hours', 8, 1, 24);
            $overtimeMultiplier = \App\Models\Setting::number('overtime_rate_multiplier', 1.5, 1, 10);

            foreach ($employees as $employee) {
                $salary = $employee->currentSalary;
                if (!$salary) continue;

                $basic      = (float) $salary->basic_salary;
                $allowances = (float) ($salary->housing_allowance + $salary->transport_allowance + $salary->other_allowances);
                $dayRate    = $basic / $totalMonthDays;
                $hourlyRate = $dayRate / $dailyWorkingHours; // ساعات العمل اليومية (إعداد daily_working_hours)

                // 1. حساب الحضور والغياب والإجازات والتأخير (من الذاكرة — بدون استعلام)
                $attendances = $allAttendances->get($employee->id, collect());
                $employeeLeaves = $allLeaves->get($employee->id, collect());

                $paidLeaveDays = 0;
                $unpaidLeaveDays = 0;

                foreach ($employeeLeaves as $leave) {
                    $leaveStart = Carbon::parse($leave->start_date)->startOfDay();
                    $leaveEnd = Carbon::parse($leave->end_date)->startOfDay();
                    $windowStart = $startDate->copy()->startOfDay();
                    $windowEnd = $endDate->copy()->startOfDay();

                    $effectiveStart = $leaveStart->greaterThan($windowStart) ? $leaveStart : $windowStart;
                    $effectiveEnd = $leaveEnd->lessThan($windowEnd) ? $leaveEnd : $windowEnd;

                    if ($effectiveStart->lessThanOrEqualTo($effectiveEnd)) {
                        $days = (int) $effectiveStart->diffInDays($effectiveEnd) + 1;
                        if ($leave->leave_type === 'unpaid') {
                            $unpaidLeaveDays += $days;
                        } else {
                            $paidLeaveDays += $days;
                        }
                    }
                }

                $presentDays         = $attendances->where('status', '!=', 'absent')->count();
                $coveredDays         = $presentDays + $paidLeaveDays;
                $unexcusedAbsentDays = max(0, $normWorkingDays - $coveredDays); // معيار أيام العمل الشهرية (إعداد monthly_working_days)
                $absentDays          = $unexcusedAbsentDays + $unpaidLeaveDays;
                $absenceCost         = $absentDays * $dayRate;

                $totalLateMinutes  = $attendances->sum('late_minutes');
                $totalOvertimeHours = (float) $attendances->sum('overtime_hours');
                $overtimeValue     = round($totalOvertimeHours * $hourlyRate * $overtimeMultiplier, 2);

                // 2. تجميع عمولات الفني (من الذاكرة — بدون استعلام)
                $commissions = (float) $allCommissions->get($employee->id, collect())->sum('commission_amount');

                // 3. تجميع الجزاءات المعتمدة (من الذاكرة — بدون استعلام)
                $approvedDeductions = (float) $allDeductions->get($employee->id, collect())->sum('amount');

                $grossSalary = round($basic + $allowances + $overtimeValue + $commissions, 2);
                $currentDeductions = round($absenceCost + $approvedDeductions, 2);
                $availableAfterCurrentDeductions = round($grossSalary - $currentDeductions, 2);

                $employeeDebt = round(
                    $outstandingDebts->get($employee->id, collect())
                        ->sum(fn ($debt) => max(0, (float) $debt->original_amount - (float) $debt->paid_amount)),
                    2
                );

                $debtRepayment = $employeeDebt > 0
                    ? min(max(0, $availableAfterCurrentDeductions), $employeeDebt)
                    : 0;

                // If current deductions exceed gross earnings, preserve the
                // unrecovered balance as an employee debt instead of losing it.
                $currentShortfall = max(0, round(-$availableAfterCurrentDeductions, 2));
                $carriedDebt = $currentShortfall;
                $netSalary = round(max(0, $availableAfterCurrentDeductions - $debtRepayment), 2);
                $allDeductionsTotal = round($currentDeductions + $debtRepayment, 2);

                $payrollItem = PayrollItem::create([
                    'payroll_id'         => $payroll->id,
                    'employee_id'        => $employee->id,
                    'basic_salary'       => $basic,
                    'total_allowance'    => $allowances + $commissions,
                    'total_deduction'    => $allDeductionsTotal,
                    'debt_repayment'     => $debtRepayment,
                    'carried_debt'       => $carriedDebt,
                    'total_overtime'     => $overtimeValue,
                    'net_salary'         => $netSalary,
                    'absent_days'        => $absentDays,
                    'late_minutes_total' => $totalLateMinutes,
                ]);

                // Link the deductions this item actually withheld (used at disbursal to mark them applied).
                $withheldDeductionIds = $allDeductions->get($employee->id, collect())->pluck('id');
                if ($withheldDeductionIds->isNotEmpty()) {
                    EmployeeDeduction::whereIn('id', $withheldDeductionIds)->update(['payroll_item_id' => $payrollItem->id]);
                }

                if ($carriedDebt > 0) {
                    EmployeePayrollDebt::create([
                        'employee_id' => $employee->id,
                        'source_payroll_item_id' => $payrollItem->id,
                        'original_amount' => $carriedDebt,
                        'paid_amount' => 0,
                    ]);
                }

                $totalBasic      += $basic;
                $totalAllowances += ($allowances + $commissions);
                $totalDeductions += $allDeductionsTotal;
                $totalNet        += $netSalary;
            }

            $payroll->update([
                'total_basic'      => $totalBasic,
                'total_allowances' => $totalAllowances,
                'total_deductions' => $totalDeductions,
                'total_net'        => $totalNet,
            ]);

            // Keep the batch in draft whenever an employee has an unrecovered
            // payroll balance. The review is explicit; the system must not
            // silently present a zero net as ready for disbursement.
            if ($payroll->items()->where('carried_debt', '>', 0)->exists()) {
                $payroll->update(['status' => 'draft']);
            }

            // إشعار المشرف العام بأن المسير جاهز للاعتماد
            $superAdmins = User::role('super-admin')->get();
            foreach ($superAdmins as $superAdmin) {
                $superAdmin->notify(new PayrollGeneratedNotification($payroll));
            }

            return $payroll;
        });
    }

    /**
     * Validate payroll header totals against its immutable item breakdown.
     *
     * The item rows are the source of truth for approval/disbursement.
     * Historical records with inconsistent stored totals must never be silently
     * approved or disbursed.
     */
    private function assertPayrollTotalsConsistent(Payroll $payroll): void
    {
        // Always re-read the items: approve/disburse must not trust a possibly stale loaded relation.
        $result = $this->computeConsistency($payroll, $payroll->items()->get());

        if (!$result['consistent']) {
            throw new Exception(
                "لا يمكن اعتماد أو صرف مسير الرواتب: إجماليات المسير لا تتطابق مع بنوده. " .
                "المتوقع صافي {$result['expected_net']} ج.م، والمسجل {$result['stored_net']} ج.م. يجب تصحيح المسير قبل المتابعة."
            );
        }
    }

    /**
     * {@inheritDoc}
     */
    public function evaluateConsistency(Payroll $payroll): array
    {
        $items = $payroll->relationLoaded('items') ? $payroll->items : $payroll->items()->get();

        return $this->computeConsistency($payroll, $items);
    }

    /**
     * Single definition of payroll consistency: the item rows are the source of truth;
     * header totals must match them and the item net must equal
     * basic + allowances + overtime - deductions + carried debt.
     *
     * @param  \Illuminate\Support\Collection<int, PayrollItem>  $items
     */
    private function computeConsistency(Payroll $payroll, $items): array
    {
        $basic = round((float) $items->sum('basic_salary'), 2);
        $allowances = round((float) $items->sum('total_allowance'), 2);
        $overtime = round((float) $items->sum('total_overtime'), 2);
        $deductions = round((float) $items->sum('total_deduction'), 2);
        $net = round((float) $items->sum('net_salary'), 2);
        $carriedDebt = round((float) $items->sum('carried_debt'), 2);

        $expectedNet = round($basic + $allowances + $overtime - $deductions + $carriedDebt, 2);

        $reasons = [];

        if (abs((float) $payroll->total_basic - $basic) > 0.01) {
            $reasons[] = 'إجمالي الأساسي في رأس المسير لا يطابق البنود.';
        }
        if (abs((float) $payroll->total_allowances - $allowances) > 0.01) {
            $reasons[] = 'إجمالي البدلات في رأس المسير لا يطابق البنود.';
        }
        if (abs((float) $payroll->total_deductions - $deductions) > 0.01) {
            $reasons[] = 'إجمالي الخصومات في رأس المسير لا يطابق البنود.';
        }
        if (abs((float) $payroll->total_net - $net) > 0.01) {
            $reasons[] = 'صافي رأس المسير لا يطابق مجموع صافي البنود.';
        }

        $netMismatch = abs($net - $expectedNet) > 0.01;
        if ($netMismatch) {
            $reasons[] = "صافي البنود ({$net}) لا يساوي الأساسي + البدلات + الإضافي - الخصومات + الرصيد المرحّل ({$expectedNet}).";
        }

        $zeroWithComponents = abs($net) < 0.01 && ($basic + $allowances > 0 || $deductions > 0);
        if ($zeroWithComponents) {
            $reasons[] = 'صافي المسير صفر رغم وجود مستحقات أو خصومات.';
        }

        return [
            'basic'                => $basic,
            'allowances'           => $allowances,
            'overtime'             => $overtime,
            'deductions'           => $deductions,
            'carried_debt'         => $carriedDebt,
            'expected_net'         => $expectedNet,
            'stored_net'           => $net,
            'zero_with_components' => $zeroWithComponents,
            'consistent'           => $reasons === [],
            'reasons'              => $reasons,
        ];
    }

    /**
     * {@inheritDoc}
     */
    public function approvePayroll(Payroll $payroll, ?int $approvedBy = null, bool $confirmDebtReview = false): bool
    {
        if ($payroll->status !== 'draft') {
            throw new Exception("المسير معتمد مسبقاً أو تم صرفه.");
        }

        $this->assertPayrollTotalsConsistent($payroll);

        $hasUnrecoveredDebt = $payroll->items()->where('carried_debt', '>', 0)->exists();

        if ($hasUnrecoveredDebt && !$confirmDebtReview) {
            throw new Exception("يوجد موظفون لديهم أرصدة رواتب غير مستردة. يجب مراجعة الرصيد المرحّل والتأكيد قبل اعتماد المسير.");
        }

        $approverId = $approvedBy ?? Auth::id();

        if (empty($approverId)) {
            throw new Exception("يجب تحديد المستخدم المعتمِد — لا يمكن اعتماد مسير الرواتب بدون تسجيل المسؤول.");
        }

        return $payroll->update([
            'status'      => 'approved',
            'approved_by' => $approverId,
        ]);
    }

    /**
     * {@inheritDoc}
     */
    public function disbursePayroll(Payroll $payroll): bool
    {
        return DB::transaction(function () use ($payroll) {
            $payroll = Payroll::query()->lockForUpdate()->findOrFail($payroll->id);

            if ($payroll->status !== 'approved') {
                throw new Exception("يجب اعتماد مسير الرواتب أولاً قبل الصرف.");
            }

            $this->assertPayrollTotalsConsistent($payroll);

            $items = $payroll->items()->lockForUpdate()->get();

            foreach ($items as $item) {
                $remainingRepayment = (float) $item->debt_repayment;

                if ($remainingRepayment <= 0) {
                    continue;
                }

                $debts = EmployeePayrollDebt::where('employee_id', $item->employee_id)
                    ->whereNull('settled_at')
                    ->lockForUpdate()
                    ->orderBy('id')
                    ->get();

                foreach ($debts as $debt) {
                    if ($remainingRepayment <= 0) {
                        break;
                    }

                    $remainingDebt = max(0, (float) $debt->original_amount - (float) $debt->paid_amount);
                    $payment = min($remainingRepayment, $remainingDebt);

                    if ($payment <= 0) {
                        continue;
                    }

                    $debt->paid_amount = round((float) $debt->paid_amount + $payment, 2);

                    if ((float) $debt->paid_amount >= (float) $debt->original_amount) {
                        $debt->paid_amount = $debt->original_amount;
                        $debt->settled_at = now();
                    }

                    $debt->save();
                    $remainingRepayment = round($remainingRepayment - $payment, 2);
                }

                if ($remainingRepayment > 0.01) {
                    throw new Exception("تعذر مطابقة كامل سداد دين الرواتب للموظف رقم {$item->employee_id}. لم يتم صرف المسير.");
                }
            }

            // Deductions withheld by this payroll are now settled: mark them applied so they are
            // immutable afterwards (DeductionService refuses status changes on applied rows).
            // Only rows linked at generation and still approved are touched; payroll math is unchanged.
            EmployeeDeduction::whereIn('payroll_item_id', $items->pluck('id'))
                ->where('status', 'approved')
                ->update(['status' => 'applied']);

            return $payroll->update([
                'status' => 'disbursed',
                'disbursed_at' => now(),
            ]);
        });
    }

    /**
     * {@inheritDoc}
     */
    public function getPayrollDetails(Payroll $payroll): Payroll
    {
        return $payroll->load(['branch', 'items.employee.jobTitle', 'approvedBy']);
    }
}
